name: github-pages

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      -
        name: build herbivore example
        run: |
          set -xe
          cd examples/herbivore
          npm i
          npm run build
      -
        name: generated dirs
        run: |
          mkdir public
          mkdir public/vanilla
          mkdir public/herbivore
      -
        name: copy static files
        run: |
          cp examples/vanilla/index.html public/vanilla
          cp examples/herbivore/dist/bundle.js public/herbivore
          cp examples/herbivore/dist/index.html public/herbivore
          cp examples/herbivore/dist/styles.css public/herbivore
      -
        name: generated index
        run: |
          cat > public/index.html <<EOL
          <!doctype html>
          <html>
            <head>
              <title>pixcellular/pxl</title>
              <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/light.css">
            </head>
            <body>
              <h1>pixcellular/pxl</h1>
              <p>Small grid framework to create ecosystem models and simulations. <br />See <a href="https://github.com/pixcellular/pxl">github</a> for more information.</p>
              <p>Examples:</p>
              <ul>
                <li><a href="./vanilla/">Vanilla</a><br />Minimal example in plain html and javascript (<a href="https://github.com/pixcellular/pxl/blob/main/examples/vanilla/">code</a>)</li>
                <li><a href="./herbivore/">Herbivore</a><br />Example structures entity behaviour with graphs and generates random maps using Perlin noise (<a href="https://github.com/pixcellular/pxl/blob/main/examples/herbivore/">code</a>)</li>
              </ul>
              <pre style="font-size: 0.8em;">(Commit <a href="https://github.com/pixcellular/pxl/commit/${{ github.sha }}">${{ github.sha }}</a>)</p>
            </body>
          </html>
          EOL
      -
        name: deploy to github pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}